apiVersion: v1
kind: Service
metadata:
    name: nginxservice
spec:
    selector:
        app: nginxpod
    ports:
    - protocol: TCP
      port: 80
      nodePort: 3010
      targetPort: nginxport

