apiVersion: v1
kind: Pod
metadata:
    name: nginxwebproxy
    label:
        app: nginxpod
Spec:
    containers:
        - name: nginx
         image: nginx:1.16.0
         ports:
            - name: nginxport
             containerPort: 80